name: Deploy to S3

on:
  push:
    branches:
      - main  # Adjust this to your default branch if different
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Adjust this if your build script is named differently

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync S3 bucket
      run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
      # Note: Change './dist' to your build output folder if different
